# 参考https://blog.csdn.net/eastmount/article/details/50824215

In [1]:
import numpy as np  
import lda  
import lda.datasets  
  
# document-term matrix  
X = lda.datasets.load_reuters()  
print("type(X): {}".format(type(X)))  
print("shape: {}\n".format(X.shape))  
print(X[:5, :5])  
  
# the vocab  
vocab = lda.datasets.load_reuters_vocab()  
print("type(vocab): {}".format(type(vocab)))  
print("len(vocab): {}\n".format(len(vocab)))  
print(vocab[:5])  
  
# titles for each story  
titles = lda.datasets.load_reuters_titles()  
print("type(titles): {}".format(type(titles)))  
print("len(titles): {}\n".format(len(titles)))  
print(titles[:5])  

type(X): <type 'numpy.ndarray'>
shape: (395L, 4258L)

[[ 1  0  1  0  0]
 [ 7  0  2  0  0]
 [ 0  0  0  1 10]
 [ 6  0  1  0  0]
 [ 0  0  0  2 14]]
type(vocab): <type 'tuple'>
len(vocab): 4258

('church', 'pope', 'years', 'people', 'mother')
type(titles): <type 'tuple'>
len(titles): 395

('0 UK: Prince Charles spearheads British royal revolution. LONDON 1996-08-20', '1 GERMANY: Historic Dresden church rising from WW2 ashes. DRESDEN, Germany 1996-08-21', "2 INDIA: Mother Teresa's condition said still unstable. CALCUTTA 1996-08-23", '3 UK: Palace warns British weekly over Charles pictures. LONDON 1996-08-25', '4 INDIA: Mother Teresa, slightly stronger, blesses nuns. CALCUTTA 1996-08-25')


In [ ]:
model = lda.LDA(n_topics=20, n_iter=500, random_state=1)  
model.fit(X)